name: assembly-readme

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'site/resources/*.adoc'

jobs:
  assembly-adoc:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [22]
        distribution: [adopt]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4.3.0

      - name: install asciidoctor-reducer
        run: sudo gem install asciidoctor-reducer

      - name: assembly readme.adoc
        run: asciidoctor-reducer --preserve-conditionals -o readme.adoc site/resources/project-readme.adoc

      - name: commit and push readme.adoc
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: readme.adoc