name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - '.github/workflows/**'
      - '.run/**'
      - '.idea/**'
      - 'site/**'

env:
  # PHP Configuration
  PHP_VERSION: 7.4

  # Github Additional Configuration
  GITHUB_REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_PROJECT_DIR: ${{ github.workspace }}
  GITHUB_TARGET_DIR: ${{ github.workspace }}/target
  GITHUB_BRANCH_NAME: ${{ github.ref_name }}
  GITHUB_UPLOAD_DIR: ${{ github.workspace }}/target/staging
  GITHUB_UPLOAD_NAME: ${{ github.event.repository.name }}.zip
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Sonarcloud Configuration
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GH}}
  SONAR_CACHE_DIR: "${HOME}/.sonar/cache"
  SONAR_HOST_URL: "https://sonarcloud.io"

  # Composer Configuration
  COMPOSER_VENDOR_DIR: ${{ github.workspace }}/vendor

  # Codacy Configuration
  CODACY_API_TOKEN: ${{ secrets.CODACY_TOKEN_GH }}

  # Coveralls Configuration
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        version: [ 22 ]
        distribution: [ adopt ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: set current timestamp
        id: TS_NOW
        run: echo "TS_NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: echo current timestamp
        run: echo ${TS_NOW} - ${{ env.TS_NOV }} - ${{ steps.TS_NOW.outputs.TS_NOW }}

      - name: checkout
        uses: actions/checkout@v4.3.0
        with:
          fetch-depth: 0

      - name: setup PHP
        uses: shivammathur/setup-php@2.35.3
        with:
          php-version: '${{ env.PHP_VERSION }}'
          coverage: xdebug
          tools: php-cs-fixer,phpstan,psalm

      - name: identify composer cache
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: cache composer packages
        uses: actions/cache@v4.2.3
        id: restore-cache
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            ${{ env.COMPOSER_VENDOR_DIR }}
          key: ${{ matrix.os }}-${{env.GITHUB_REPO_NAME}}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{env.GITHUB_REPO_NAME}}-composer-

      - name: install dependencies
        run: composer update --no-ansi --no-interaction --no-progress

      - name: build
        run: composer c-package

      - name: upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ env.GITHUB_UPLOAD_NAME }}.zip
          path: ${{ env.GITHUB_UPLOAD_DIR }}/*-${{ env.GITHUB_UPLOAD_NAME }}*.zip
          if-no-files-found: warn
          retention-days: 7
